### PR TITLE
Update manifest.json

### LINKED ISSUE #152: No 'version' key in the manifest file for custom integration 'alarmo'.
Getting this notification in Log when starting HA ith latest version installed v1.5.3:

2021-03-03 22:28:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-03 22:28:03 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'alarmo'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'alarmo'

### PR DESCRIPTION
**Pull request by isabellaalstrom**
Add version to manifest.json according to new requirements for custom components. I added an extra patch-version from the latest release, as to be able to release v1.5.4 with this change directly. Fixes #152

### CODE REVIEW

**Comment by nielsfaber** [comment]
Thanks for your efforts!
I’m aware of this new requirement, but I am investigating how to automatically place the correct version number (its also hard-coded in the component as well as the card). 
Keeping the version in sync in 3 places is doomed for failures..
I am planning on releasing a fix within a week.

**Comment by isabellaalstrom** [comment]
I see! Maybe write this in the issue as well then :)

**Comment by ludeeus** [comment]
I use this workflow in multiple integrations <https://github.com/custom-components/breaking_changes/blob/main/.github/workflows/release.yaml>

**Comment by nielsfaber** [comment]
@isabellaalstrom I finally managed to create a script that automatically creates a zip with updated version in the manifest.json upon release. It's pretty similar to the script @ludeeus has made.
I'm afraid this PR became obsolete, sorry for closing it. 
There's a new release of Alarmo which should get rid of the warning in the HA log.

**Comment by isabellaalstrom** [comment]
Don't worry about it :)

**Pull request closed without merging**
