### PR TITLE
Update hacs.json

### PR DESCRIPTION
**Pull request by dennisstorm-lab**
Set the HASS version to the most recent non-BETA version

### CODE REVIEW

**Comment by nielsfaber** [comment]
Why is this needed? I understand from HACS documentation that the non-beta releases will also be passing this condition.

**Comment by dennisstorm-lab** [comment]
You have the following in hacs.json: homeassistant: "2023.4.0b1"

The docs state: "Allow Home Assistant beta versions by appending b0. Without b0, only official releases will be allowed."
This is ofcourse perfectly valid, since you only want to deploy on official HASS releases.

However, since 2023.4.0b1 is HIGHER than 2023.3.6 nothing gets installed, which is the issue.

The 'homeassistant" value should contain the minimum required version. Since practically no-one has a BETA running, which is higher than the current HASS release installation will not happen.

image

**Comment by nielsfaber** [comment]
My intention was to have v1.9.7 show up as latest available version for users who are on HA 2023.3 or lower.
And to have v1.9.8 show up for users who are on HA 2023.4 (beta or alpha).
If I understand you correctly, pinning to HA 2023.4 in the hacs.json file causes the entire Alarmo project to require HA 2023.4, which is not what I wanted.
In this case I rather remove the pinning completely, HACS documentation is not very clear on this.

**Comment by nielsfaber** [comment]
I tried this in my own HA installation.
With HA 2023.3 installed.

V1.9.7 shows up as OK for download:
image

V1.9.8 shows up as incompatible:
image

After updating to HA 2023.4, V1.9.8 shows up as available for download:
image

All seems to work as intended so we can close this PR.

**Pull request closed without merging**
