### PR TITLE
Broadlink s1c Alarm

### PR DESCRIPTION
**Pull request by rucanunes**
Please add intregration to Broadlink s1c Alarm. Thank you!

### CODE REVIEW

**Comment by nielsfaber** [comment]
I cannot review this PR.
It contains 39 commits, changes to 27 files and I don’t know what is BroadLink s1c.
Can you please elaborate?

**Comment by rucanunes** [comment]
Hi,
Thank you for your time. When I install the add on it can't find my sensors...
They are named like this: 

```
Motion Sensor:
sensor.porta_da_sala_de_estar

Door/Window Sensor:
sensor.porta_do_escritorio

Arm/Disarm:
switch.armar_outdoor
```

Any idea on how can go around this?

Thank you!

**Comment by nielsfaber** [comment]
A PR is not the place for asking support questions. It is the place for submitting changes to the code.
I ask you again: what is this PR about? I don’t understand what you are trying to achieve.

**Comment by rucanunes** [comment]
Hi,
Thank you for your time. When I install the add on it can't find my sensors...
They are named like this: 

```
Motion Sensor:
sensor.porta_da_sala_de_estar

Door/Window Sensor:
sensor.porta_do_escritorio

Arm/Disarm:
switch.armar_outdoor
```

Any idea on how can go around this?

Thank you!

**Comment by rucanunes** [comment]
When I try to add sensors or the alarm my sensors are not binary, so they don't show up..
Is there a way I can fix that?

**Comment by nielsfaber** [comment]
I’m closing the PR because you are ignoring my questions.
You can use the HA forum thread for Alarmo or the GitHub issues for your questions.

**Pull request closed without merging**
