### PR TITLE
Fix `FORMAT_NUMBER` depreciation

### LINKED ISSUE #864: Breaking changes in HA 2024.1 beta
### Alarmo Version

v1.9.13

### HA Version

2024.1b2

### Bug description

```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:204
Integration: Alarm control panel ([documentation](https://rc.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: December 30, 2023 at 23:56:38 (2 occurrences)
Last logged: December 30, 2023 at 23:56:38

FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues
```

### Steps to reproduce

Install the latest HA beta.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by TheZoker**
Fixes #864

### CODE REVIEW

**Comment by bernardesarthur** [comment]
Hi Zoker, I tested here and it is work's fine. Thank's!

**Review by codyc1515 — APPROVED** [review]
This worked for me.

**Comment by smarthomefamilyverrips** [comment]
worked for me also to eliminate the log message as described in #870

**Comment by TheZoker** [comment]
@nielsfaber Would be amazing if you could have a look at this 😊

**Comment by nielsfaber** [comment]
Looks good to me, thanks 👍

**Pull request merged**
