### PR TITLE
Create ru.json

### PR DESCRIPTION
**Pull request by Allkorolev**
Added Russian translation

### CODE REVIEW

**Comment by IncognitoMSK** [comment]
Can you tell me how to fix the localization?

**Comment by angelicaruta** [comment]
[ru.zip](https://github.com/nielsfaber/alarmo/files/10775201/ru.zip)
json couldn't load, so in zip

**Comment by IncognitoMSK** [comment]
Thanks for the files, I uploaded it to the server, but the ru language did not appear, tell me how to turn it on

**Comment by nielsfaber** [comment]
Duplicate of #682

**Pull request closed without merging**
